# Generated by Django 5.1.5 on 2025-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0005_rename_first_name_waiter_waiter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='waiter_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
