# Generated by Django 5.1.5 on 2025-01-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0006_alter_waiter_waiter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant_id',
        ),
        
        migrations.AlterField(
            model_name='waiter',
            name='waiter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
