# Generated by Django 5.1.5 on 2025-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0007_remove_customuser_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
