# Generated by Django 5.1.5 on 2025-02-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0010_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('waiter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='loginauth.waiter')),
            ],
        ),
    ]
