# Generated by Django 5.1.5 on 2025-02-19 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0012_remove_table_waiter_id_alter_table_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('dinein', 'Dine In'), ('takeaway', 'Take Away')], max_length=10)),
                ('table_number', models.CharField(max_length=10)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginauth.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginauth.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loginauth.order')),
            ],
        ),
    ]
