# Generated by Django 5.1.5 on 2025-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0003_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
