# Generated by Django 5.1.5 on 2025-01-28 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0004_waiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='first_name',
            new_name='waiter_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='last_name',
        ),
       
        
        migrations.AddField(
            model_name='waiter',
            name='waiter_id',
            field=models.CharField( max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
       
        
        migrations.AlterField(
            model_name='waiter',
            name='hire_date',
            field=models.DateField(),
        ),


        #  adding manually
        migrations.AddField(
            model_name='customuser',
            name='restaurant_id',
            field=models.CharField( max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        
        migrations.AddField(
            model_name='waiter',
            name='restaurant_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),


        
    ]
