# Generated by Django 5.1.5 on 2025-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], max_length=10)),
                ('section', models.CharField(choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
