# Generated by Django 5.1.5 on 2025-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0011_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='waiter_id',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
