# Generated by Django 5.1.5 on 2025-03-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0013_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderTicket',
            fields=[
                ('kot_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot', to='loginauth.order')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginauth.menuitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginauth.orderitem')),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loginauth.kitchenorderticket')),
            ],
        ),
    ]
