# Generated by Django 5.1.5 on 2025-04-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0014_kitchenorderticket_kitchenorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginauth.kitchenorderticket')),
            ],
        ),
    ]
