# Generated by Django 5.1.5 on 2025-04-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0016_orderitem_gst_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sgst',
        ),
    ]
