# Generated by Django 5.1.5 on 2025-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0017_remove_bill_cgst_remove_bill_sgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='kot',
        ),
        migrations.AddField(
            model_name='bill',
            name='kot',
            field=models.ManyToManyField(to='loginauth.kitchenorderticket'),
        ),
    ]
