# Generated by Django 5.1.5 on 2025-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0019_item_supplier_stockout_stockin_item_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
