# Generated by Django 5.1.5 on 2025-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0020_remove_item_category_remove_supplier_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Litre'), ('pcs', 'Pieces'), ('pkt', 'Packet'), ('dozen', 'Dozen')], max_length=10),
        ),
    ]
