# Generated by Django 5.1.5 on 2025-05-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0021_rename_price_stockin_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginauth.supplier'),
        ),
    ]
