# Generated by Django 5.1.5 on 2025-07-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0023_alter_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
