# Generated by Django 5.1.5 on 2025-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0024_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('table_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
